version: '2'
services:
  time-weather:
    container_name: time-weather
    image: node:8.9
    working_dir: /usr/src/app/
    command: bash -c 'yarn install && yarn run devserver'
    volumes:
      - ./:/usr/src/app/
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=3000
      - SKY_DARK_URI="URI WITH KEY"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"